In [14]:
import numpy as np

In [15]:
np.__version__

'1.26.4'

In [16]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

Creating list

In [18]:
list1 = [1,2,3,4,5,6]
list1

[1, 2, 3, 4, 5, 6]

In [20]:
type(list1)

list

In [22]:
arr = np.array(list1)

In [23]:
type(arr)

numpy.ndarray

In [24]:
type(list1)

list

Arange Function

In [25]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [30]:
np.arange(int(5.0))

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(9)


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [33]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [34]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [39]:
np.arange(20,10)

array([], dtype=int32)

In [40]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [42]:
np.arange(10,20,30)

array([10])

In [43]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [45]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

Zeroes

In [50]:
np.zeros(10,dtype=int) #hyper parameter turnary 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [51]:
np.zeros(20,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [55]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [59]:
np.zeros((4,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [62]:
np.zeros((8,8),dtype=int) # left side refering to ROW , right side refering to COLUMN.

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [64]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [66]:
np.zeros((8,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

ONES

In [67]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [68]:
np.ones((4,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [70]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

Rand

In [82]:
np.random.rand(10,5) #every time it will give ur different output of random values 

array([[0.14711922, 0.76847083, 0.22282342, 0.46234297, 0.33379105],
       [0.48860795, 0.00782236, 0.44786643, 0.83154814, 0.75598367],
       [0.96993493, 0.55875978, 0.51158813, 0.71152901, 0.33878818],
       [0.06076282, 0.5046475 , 0.55009065, 0.13327653, 0.14184874],
       [0.6101246 , 0.85907688, 0.23908798, 0.64135258, 0.65361711],
       [0.11178086, 0.27367831, 0.82887045, 0.22904556, 0.94961119],
       [0.75535386, 0.12066756, 0.49288213, 0.23161795, 0.36443594],
       [0.93854099, 0.06928129, 0.63314914, 0.74978829, 0.62659206],
       [0.33855328, 0.2598029 , 0.25367411, 0.65154989, 0.80289421],
       [0.12926916, 0.93925939, 0.6620539 , 0.91595953, 0.39715529]])

Randint

In [90]:
np.random.randint(5,10) #it will give exclusive value by not giving 10 bwtween 5 and 10

9

In [95]:
np.random.randint(2,20,3) #it will give 3 random values between 2 and 20 but not including 20.

array([14, 12, 17])

In [ ]:
np.random.randint(5,20,8) ##it will give 8 random values between 5 and 20 but not including 20.

array([12, 16, 18,  9,  7, 17, 19, 12])