Slicing in Matrix

In [25]:
import numpy as np  

In [26]:
import sys

In [27]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

Reshape

In [28]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [30]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [31]:
np.arange(1,21).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [32]:
np.arange(1,25).reshape(6,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

Slicing in Matrix

In [33]:
b = np.random.randint(10,20,(5,4))
b

array([[11, 10, 16, 15],
       [13, 19, 11, 15],
       [12, 13, 19, 18],
       [12, 13, 16, 15],
       [18, 11, 10, 19]])

In [34]:
type(b)

numpy.ndarray

In [35]:
b[:]

array([[11, 10, 16, 15],
       [13, 19, 11, 15],
       [12, 13, 19, 18],
       [12, 13, 16, 15],
       [18, 11, 10, 19]])

In [36]:
b[1:3]

array([[13, 19, 11, 15],
       [12, 13, 19, 18]])

In [37]:
b[1:-1]

array([[13, 19, 11, 15],
       [12, 13, 19, 18],
       [12, 13, 16, 15]])

In [38]:
b[2:3]

array([[12, 13, 19, 18]])

In [39]:
b[2:4]

array([[12, 13, 19, 18],
       [12, 13, 16, 15]])

Operations

In [40]:
a = np.random.randint(0,100,(10,10)) #we create a 10x10 array with random integers between 0 and 100
a

array([[82, 75, 38, 81, 35, 45, 74, 11,  9, 77],
       [72, 19, 74, 84, 34, 37, 74, 67, 44, 46],
       [63, 17, 47,  3, 90, 76, 57, 99, 27, 92],
       [22, 81, 30, 80,  9, 37, 81, 57, 13, 33],
       [48, 39, 77, 38, 49, 74, 41, 16, 90, 89],
       [33, 40, 96, 90, 73, 20, 69, 51, 86,  6],
       [89, 18, 29,  4, 60, 64, 34, 85, 23,  2],
       [77, 70,  2, 65, 54, 41, 43, 98, 93, 61],
       [98, 38,  1, 44,  1, 86, 31, 65, 66, 13],
       [74, 56, 13, 22, 88, 45, 43, 99, 20, 64]])

In [48]:
a [::-2]

array([[74, 56, 13, 22, 88, 45, 43, 99, 20, 64],
       [77, 70,  2, 65, 54, 41, 43, 98, 93, 61],
       [33, 40, 96, 90, 73, 20, 69, 51, 86,  6],
       [22, 81, 30, 80,  9, 37, 81, 57, 13, 33],
       [72, 19, 74, 84, 34, 37, 74, 67, 44, 46]])

In [49]:
a[::-3]

array([[74, 56, 13, 22, 88, 45, 43, 99, 20, 64],
       [89, 18, 29,  4, 60, 64, 34, 85, 23,  2],
       [22, 81, 30, 80,  9, 37, 81, 57, 13, 33],
       [82, 75, 38, 81, 35, 45, 74, 11,  9, 77]])

In [ ]:
print(a)
print(a[0:10:3]) #in this case it will give give us 0th index row and after that every 3rd row until the end of the 10th row

[[82 75 38 81 35 45 74 11  9 77]
 [72 19 74 84 34 37 74 67 44 46]
 [63 17 47  3 90 76 57 99 27 92]
 [22 81 30 80  9 37 81 57 13 33]
 [48 39 77 38 49 74 41 16 90 89]
 [33 40 96 90 73 20 69 51 86  6]
 [89 18 29  4 60 64 34 85 23  2]
 [77 70  2 65 54 41 43 98 93 61]
 [98 38  1 44  1 86 31 65 66 13]
 [74 56 13 22 88 45 43 99 20 64]]
[[82 75 38 81 35 45 74 11  9 77]
 [22 81 30 80  9 37 81 57 13 33]
 [89 18 29  4 60 64 34 85 23  2]
 [74 56 13 22 88 45 43 99 20 64]]


In [53]:
a.max()

99

In [54]:
a.min()

1

In [56]:
a.mean()

51.96

Indexing

In [63]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [64]:
row = 5
column = 4

In [65]:
column

4

In [66]:
row

5

In [74]:
mat [row,column]

54

In [75]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [81]:
mat[:,3]

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

In [82]:
mat[row,:]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [84]:
mat[:, column] 

array([ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94])

In [85]:
mat[:column]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [86]:
mat[row:]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [87]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [88]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [89]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [90]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [93]:
mat[1:5]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [94]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [95]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [96]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [97]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [99]:
mat[::-2]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [100]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [101]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [102]:
mat[2:6,2:5]

array([[22, 23, 24],
       [32, 33, 34],
       [42, 43, 44],
       [52, 53, 54]])

Masking